# -*- coding: utf-8 -*-
"""
报纸源配置模块
定义预设报纸及其下载适配器，支持扩展自定义报纸源
"""

# 报纸源配置结构：
# - id: 唯一标识符
# - name: 显示名称
# - adapter: 下载适配器类名（在 downloader 模块中实现）
# - enabled: 是否可用（某些源可能因网站改版暂时失效）
# - description: 简要说明
# - category: 分类（综合报纸 / 省市日报）

# 报纸分类（用于 UI 单选筛选）
NEWSPAPER_CATEGORIES = [
    ("综合报纸", "zhonghe"),   # (显示名, 内部标识)
    ("省市日报", "shengshi"),
]

# 在线报纸阅读入口（求是网·党报党刊）
ONLINE_NEWSPAPER_URL = "https://www.qstheory.cn/v9zhuanqu/resource/dbdk/index.htm"

NEWSPAPER_SOURCES = [
    {
        "id": "rmrb",
        "name": "人民日报",
        "adapter": "PeopleDailyAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "人民网电子版，支持分页下载合并为 PDF",
    },
    {
        "id": "xinhua",
        "name": "新华每日电讯",
        "adapter": "XinhuaAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "新华社主办，来源 mrdx.cn 电子版",
    },
    {
        "id": "gmrb",
        "name": "光明日报",
        "adapter": "GuangmingAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "光明网电子版，来源 epaper.gmw.cn（官网或暂未提供 PDF）",
    },
    {
        "id": "jjrb",
        "name": "经济日报",
        "adapter": "EconomicDailyAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "经济日报电子版",
    },
    {
        "id": "zgjjsb",
        "name": "中国经济时报",
        "adapter": "CETimesAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "中国经济时报电子版，来源 jjsb.cet.com.cn",
    },
    {
        "id": "zglyb",
        "name": "中国旅游报",
        "adapter": "CTNewsAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "中国旅游报电子版，来源 ctnews.com.cn",
    },
    {
        "id": "zgwhb",
        "name": "中国文化报",
        "adapter": "CCMAppAdapter",
        "enabled": True,
        "category": "zhonghe",
        "description": "中国文化报数字报，来源 npaper.ccmapp.cn",
    },
    # 省市日报（可继续添加各省市日报）
    {
        "id": "bjrb",
        "name": "北京日报",
        "adapter": "BeijingDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "北京日报电子版，来源 bjrbdzb.bjd.com.cn",
    },
    {
        "id": "tjrb",
        "name": "天津日报",
        "adapter": "TianjinDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "天津日报电子版，来源 epaper.tianjinwe.com",
    },
    {
        "id": "cqrb",
        "name": "重庆日报",
        "adapter": "ChongqingDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "重庆日报电子版，来源 epaper.cqrb.cn",
    },
    {
        "id": "hbrb",
        "name": "河北日报",
        "adapter": "HebeiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "河北日报电子版，来源 hbrb.hebnews.cn",
    },
    {
        "id": "sxrb",
        "name": "山西日报",
        "adapter": "ShanxiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "山西日报电子版，来源 epaper.sxrb.com",
    },
    {
        "id": "nmgrb",
        "name": "内蒙古日报",
        "adapter": "InnerMongoliaDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "内蒙古日报电子版，来源 szb.northnews.cn",
    },
    {
        "id": "dzrb",
        "name": "大众日报",
        "adapter": "DazhongDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "大众日报电子版，来源 paper.dzwww.com",
    },
    {
        "id": "hljrb",
        "name": "黑龙江日报",
        "adapter": "HeilongjiangDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "黑龙江日报电子版，来源 epaper.hljnews.cn",
    },
    {
        "id": "jlrb",
        "name": "吉林日报",
        "adapter": "JilinDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "吉林日报电子版，来源 jlrbszb.dajilin.com",
    },
    {
        "id": "lnrb",
        "name": "辽宁日报",
        "adapter": "LiaoningDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "辽宁日报电子版，来源 epaper.lnd.com.cn",
    },
    {
        "id": "xhrb",
        "name": "新华日报",
        "adapter": "XinhuaJiangsuDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "新华日报（江苏）电子版，来源 xh.xhby.net",
    },
    {
        "id": "zjrb",
        "name": "浙江日报",
        "adapter": "ZhejiangDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "浙江日报电子版，来源 zjrb.zjol.com.cn",
    },
    {
        "id": "ahrb",
        "name": "安徽日报",
        "adapter": "AnhuiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "安徽日报电子版，来源 szb.ahnews.com.cn",
    },
    {
        "id": "jxrb",
        "name": "江西日报",
        "adapter": "JiangxiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "江西日报电子版，来源 jiangxi.jxnews.com.cn",
    },
    {
        "id": "fjrb",
        "name": "福建日报",
        "adapter": "FujianDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "福建日报电子版，来源 fjrb.fjdaily.com",
    },
    {
        "id": "hnrb",
        "name": "河南日报",
        "adapter": "HenanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "河南日报电子版，来源 newpaper.dahe.cn",
    },
    {
        "id": "hbrb_hb",
        "name": "湖北日报",
        "adapter": "HubeiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "湖北日报电子版，来源 epaper.hubeidaily.net",
    },
    {
        "id": "hnrb_hn",
        "name": "湖南日报",
        "adapter": "HunanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "湖南日报电子版，来源 hnrb.voc.com.cn",
    },
    {
        "id": "nfrb",
        "name": "南方日报",
        "adapter": "SouthernDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "南方日报电子版，来源 epaper.southcn.com",
    },
    {
        "id": "gxrb",
        "name": "广西日报",
        "adapter": "GuangxiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "广西日报电子版，来源 gxrb.gxrb.com.cn",
    },
    {
        "id": "harb",
        "name": "海南日报",
        "adapter": "HainanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "海南日报电子版，来源 news.hndaily.cn",
    },
    {
        "id": "gzrb",
        "name": "贵州日报",
        "adapter": "GuizhouDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "贵州日报电子版，来源 szb.eyesnews.cn",
    },
    {
        "id": "scrb",
        "name": "四川日报",
        "adapter": "SichuanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "四川日报电子版，来源 epaper.scdaily.cn",
    },
    {
        "id": "ynrb",
        "name": "云南日报",
        "adapter": "YunnanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "云南日报电子版，来源 yndaily.yunnan.cn（pad 版）",
    },
    {
        "id": "xzrb",
        "name": "西藏日报",
        "adapter": "XizangDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "西藏日报电子版，来源 e.xzxw.com",
    },
    {
        "id": "sxrb_sn",
        "name": "陕西日报",
        "adapter": "ShaanxiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "陕西日报电子版，来源 esb.sxdaily.com.cn",
    },
    {
        "id": "gsrb",
        "name": "甘肃日报",
        "adapter": "GansuDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "甘肃日报电子版，来源 szb.gansudaily.com.cn",
    },
    {
        "id": "qhrb",
        "name": "青海日报",
        "adapter": "QinghaiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "青海日报电子版，来源 epaper.tibet3.com（移动版）",
    },
    {
        "id": "nxrb",
        "name": "宁夏日报",
        "adapter": "NingxiaDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "宁夏日报电子版，来源 szb.nxrb.cn",
    },
    {
        "id": "xjrb",
        "name": "新疆日报",
        "adapter": "XinjiangDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "新疆日报电子版，来源 xjrb.ts.cn",
    },
    {
        "id": "btrb",
        "name": "兵团日报",
        "adapter": "BingtuanDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "兵团日报电子版，来源 epaper.bingtuannet.com",
    },
    {
        "id": "whb",
        "name": "文汇报",
        "adapter": "WenhuiDailyAdapter",
        "enabled": True,
        "category": "shengshi",
        "description": "文汇报电子版，来源 shobserver.com",
    },
]
